#!/usr/bin/env ruby

require 'mongo'
require 'optparse'
require 'resolv'

def print_documents(documents)
  name_length = documents.map { |document| document[:Name].length }
  max_name_length = name_length.max

  ipv6_size = documents.map { |document| document[:IPv6].size }
  max_ipv6_size = ipv6_size.max

  ipv4_size = documents.map { |document| document[:IPv4].size }
  max_ipv4_size = ipv4_size.max

  documents.each do |document|
    format = sprintf('%%-%ds', max_name_length)
    message = sprintf(format, document[:Name])

    max_ipv6_size.times do |i|
      message += sprintf('  %-39s', document[:IPv6][i])
    end

    max_ipv4_size.times do |i|
      message += sprintf('  %-15s', document[:IPv4][i])
    end

    puts message
  end
end

def list(collection)
  documents = collection.find(nil, { :sort => { :Name => 1 } })

  print_documents(documents)
end

def search(collection, *a)
  documents = []

  a.each do |s|
    if s =~ Resolv::IPv6::Regex
      filter = { :IPv6 => s }
    elsif s =~ Resolv::IPv4::Regex
      filter = { :IPv4 => s }
    else
      filter = { :Name => s }
    end

    docs = collection.find(filter, { :sort => { :Name => 1 } })
    docs.each do |doc|
      documents.push(doc)
    end
  end

  print_documents(documents)
end

def add(collection, name, *a)
  ipv6_list = []
  ipv4_list = []

  a.each do |s|
    if s =~ Resolv::IPv6::Regex
      ipv6_list.push(s)
    elsif s =~ Resolv::IPv4::Regex
      ipv4_list.push(s)
    end
  end

  document = { :Name => name, :IPv6 => ipv6_list, :IPv4 => ipv4_list }
  collection.insert_one(document)
end

def delete(collection, *a)
  a.each do |s|
    filter = { :Name => s }

    collection.find_one_and_delete(filter)
  end
end

opts = ARGV.getopts('h:P:u:p:')
host = opts['h'] ? opts['h'] : 'localhost'
port = opts['P'] ? opts['P'] : '27017'
user = opts['u']
pass = opts['p']

if user.nil? or pass.nil?
  uri = sprintf('mongodb://%s:%s/host', host, port)
else
  uri = sprintf('mongodb://%s:%s@%s:%s/host', user, pass, host, port)
end

Mongo::Logger.logger = Logger.new(STDERR)
Mongo::Logger.level = Logger::INFO

client = Mongo::Client.new(uri)
collection = Mongo::Collection.new(client.database, 'ip')

command = ARGV.shift
case command
when nil, 'l', 'list'
  list(collection)
when 's', 'search'
  search(collection, *ARGV)
when 'a', 'add'
  name = ARGV.shift
  add(collection, name, *ARGV)
when 'd', 'delete'
  delete(collection, *ARGV)
else
  ARGV.unshift(command)
  search(collection, *ARGV)
end

client.close

exit 0
