#!/usr/bin/env ruby

require 'google/cloud/firestore'
require 'optparse'
require 'resolv'

def list(collection)
  collection.get do |host|
    name = host[:Name]
    ipv6 = host[:IPv6].join(' ')
    ipv4 = host[:IPv4].join(' ')

    message = sprintf('%-14s  %-39s  %-31s', name, ipv6, ipv4)
    puts message
  end
end

def search(collection, s)
  if s =~ Resolv::IPv6::Regex
    query = collection.where('IPv6', 'array-contains', s)
  elsif s =~ Resolv::IPv4::Regex
    query = collection.where('IPv4', 'array-contains', s)
  else
    query = collection.where('Name', '=', s)
  end

  query.get do |host|
    name = host[:Name]
    ipv6 = host[:IPv6].join(' ')
    ipv4 = host[:IPv4].join(' ')

    message = sprintf('%-14s  %-39s  %-31s', name, ipv6, ipv4)
    puts message
  end
end

def add(collection, name, ipv6, ipv4)
  ipv6_list = ipv6.split(',')
  ipv4_list = ipv4.split(',')

  doc_ref = collection.doc(name)
  doc_ref.set(
    Type: 'server',
    Name: name,
    IPv6: ipv6_list,
    IPv4: ipv4_list
  )
end

def delete(collection, name)
  doc_ref = collection.doc(name)
  doc_ref.delete
end

opts = ARGV.getopts('c:p:')
project_id = opts['p']
collection_name = opts['c']
if project_id.nil? or collection_name.nil?
  STDERR.puts 'options must be specified'
  exit 1
end

firestore = Google::Cloud::Firestore.new(project_id: project_id)
collection = firestore.col(collection_name)

command = ARGV.shift
case command
when nil, 'l', 'list'
  list(collection)
when 's', 'search'
  search(collection, *ARGV)
when 'a', 'add'
  add(collection, *ARGV)
when 'd', 'delete'
  delete(collection, *ARGV)
else
  search(collection, command)
end

exit 0
