#!/usr/bin/env ruby

require 'google/cloud/firestore'
require 'optparse'
require 'resolv'

HOSTS_COLLECTION_NAME = 'Hosts'

def list(firestore)
  hosts_ref = firestore.col(HOSTS_COLLECTION_NAME)
  hosts_ref.get do |host|
    name = host[:Name]
    ipv6 = host[:IPv6].join(' ')
    ipv4 = host[:IPv4].join(' ')

    message = sprintf('%-14s  %-39s  %-31s', name, ipv6, ipv4)
    puts message
  end
end

def search(firestore, s)
  hosts_ref = firestore.col(HOSTS_COLLECTION_NAME)

  if s =~ Resolv::IPv6::Regex
    query = hosts_ref.where('IPv6', 'array-contains', s)
  elsif s =~ Resolv::IPv4::Regex
    query = hosts_ref.where('IPv4', 'array-contains', s)
  else
    query = hosts_ref.where('Name', '=', s)
  end

  query.get do |host|
    name = host[:Name]
    ipv6 = host[:IPv6].join(' ')
    ipv4 = host[:IPv4].join(' ')

    message = sprintf('%-14s  %-39s  %-31s', name, ipv6, ipv4)
    puts message
  end
end

def add(firestore, name, ipv6, ipv4)
  ipv6_list = ipv6.split(',')
  ipv4_list = ipv4.split(',')

  doc_name = HOSTS_COLLECTION_NAME + '/' + name
  doc_ref = firestore.doc(doc_name)
  doc_ref.set(
    Type: 'server',
    Name: name,
    IPv6: ipv6_list,
    IPv4: ipv4_list
  )
end

def delete(firestore, name)
  doc_name = HOSTS_COLLECTION_NAME + '/' + name
  doc_ref = firestore.doc(doc_name)
  doc_ref.delete
end

opts = ARGV.getopts('p:')
project_id = opts['p']
unless project_id
  STDERR.puts 'project id not defined'
  exit 1
end

firestore = Google::Cloud::Firestore.new(project_id: project_id)

unless ARGV[0]
  list(firestore)
end

case ARGV[0]
when 'l', 'list'
  list(firestore)
when 's', 'search'
  search(firestore, ARGV[1])
when 'a', 'add'
  add(firestore, ARGV[1], ARGV[2], ARGV[3])
when 'd', 'delete'
  delete(firestore, ARGV[1])
else
  search(firestore, ARGV[0])
end
